apiVersion: v1
kind: Service
metadata:
    name: "akskodey-433c"
    labels:
        app: "akskodey-433c"
spec:
    type: LoadBalancer
    ports:
    - port: 
      targetPort: 
      protocol: TCP
      name: http
    selector:
        app: "akskodey-433c"